<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260415181940 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE genre (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE genre_film (genre_id INT NOT NULL, film_id INT NOT NULL, PRIMARY KEY (genre_id, film_id))');
        $this->addSql('CREATE INDEX IDX_6381FFB8708A0E0 ON genre_film (genre_id)');
        $this->addSql('CREATE INDEX IDX_6381FFB8567F5183 ON genre_film (film_id)');
        $this->addSql('ALTER TABLE genre_film ADD CONSTRAINT FK_6381FFB8708A0E0 FOREIGN KEY (genre_id) REFERENCES genre (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE genre_film ADD CONSTRAINT FK_6381FFB8567F5183 FOREIGN KEY (film_id) REFERENCES film (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE genre_film DROP CONSTRAINT FK_6381FFB8708A0E0');
        $this->addSql('ALTER TABLE genre_film DROP CONSTRAINT FK_6381FFB8567F5183');
        $this->addSql('DROP TABLE genre');
        $this->addSql('DROP TABLE genre_film');
    }
}
