<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260422095103 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE basket (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE lang (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE programme (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, room_id INT NOT NULL, film_id INT NOT NULL, lang_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3DDCB9FF54177093 ON programme (room_id)');
        $this->addSql('CREATE INDEX IDX_3DDCB9FF567F5183 ON programme (film_id)');
        $this->addSql('CREATE INDEX IDX_3DDCB9FFB213FA4 ON programme (lang_id)');
        $this->addSql('CREATE TABLE reservation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, programme_id INT NOT NULL, basket_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_42C8495562BB7AEE ON reservation (programme_id)');
        $this->addSql('CREATE INDEX IDX_42C849551BE1FB52 ON reservation (basket_id)');
        $this->addSql('CREATE TABLE reservation_seat (reservation_id INT NOT NULL, seat_id INT NOT NULL, PRIMARY KEY (reservation_id, seat_id))');
        $this->addSql('CREATE INDEX IDX_2B65FB0EB83297E7 ON reservation_seat (reservation_id)');
        $this->addSql('CREATE INDEX IDX_2B65FB0EC1DAFE35 ON reservation_seat (seat_id)');
        $this->addSql('CREATE TABLE room (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, capacity INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE seat (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, number INT NOT NULL, class INT NOT NULL, room_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3D5C366654177093 ON seat (room_id)');
        $this->addSql('ALTER TABLE programme ADD CONSTRAINT FK_3DDCB9FF54177093 FOREIGN KEY (room_id) REFERENCES room (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE programme ADD CONSTRAINT FK_3DDCB9FF567F5183 FOREIGN KEY (film_id) REFERENCES film (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE programme ADD CONSTRAINT FK_3DDCB9FFB213FA4 FOREIGN KEY (lang_id) REFERENCES lang (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE reservation ADD CONSTRAINT FK_42C8495562BB7AEE FOREIGN KEY (programme_id) REFERENCES programme (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE reservation ADD CONSTRAINT FK_42C849551BE1FB52 FOREIGN KEY (basket_id) REFERENCES basket (id)');
        $this->addSql('ALTER TABLE reservation_seat ADD CONSTRAINT FK_2B65FB0EB83297E7 FOREIGN KEY (reservation_id) REFERENCES reservation (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE reservation_seat ADD CONSTRAINT FK_2B65FB0EC1DAFE35 FOREIGN KEY (seat_id) REFERENCES seat (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE seat ADD CONSTRAINT FK_3D5C366654177093 FOREIGN KEY (room_id) REFERENCES room (id) NOT DEFERRABLE');
        $this->addSql('ALTER INDEX idx_6381ffb8708a0e0 RENAME TO IDX_39A967D24296D31F');
        $this->addSql('ALTER INDEX idx_6381ffb8567f5183 RENAME TO IDX_39A967D2567F5183');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE programme DROP CONSTRAINT FK_3DDCB9FF54177093');
        $this->addSql('ALTER TABLE programme DROP CONSTRAINT FK_3DDCB9FF567F5183');
        $this->addSql('ALTER TABLE programme DROP CONSTRAINT FK_3DDCB9FFB213FA4');
        $this->addSql('ALTER TABLE reservation DROP CONSTRAINT FK_42C8495562BB7AEE');
        $this->addSql('ALTER TABLE reservation DROP CONSTRAINT FK_42C849551BE1FB52');
        $this->addSql('ALTER TABLE reservation_seat DROP CONSTRAINT FK_2B65FB0EB83297E7');
        $this->addSql('ALTER TABLE reservation_seat DROP CONSTRAINT FK_2B65FB0EC1DAFE35');
        $this->addSql('ALTER TABLE seat DROP CONSTRAINT FK_3D5C366654177093');
        $this->addSql('DROP TABLE basket');
        $this->addSql('DROP TABLE lang');
        $this->addSql('DROP TABLE programme');
        $this->addSql('DROP TABLE reservation');
        $this->addSql('DROP TABLE reservation_seat');
        $this->addSql('DROP TABLE room');
        $this->addSql('DROP TABLE seat');
        $this->addSql('ALTER INDEX idx_39a967d2567f5183 RENAME TO idx_6381ffb8567f5183');
        $this->addSql('ALTER INDEX idx_39a967d24296d31f RENAME TO idx_6381ffb8708a0e0');
    }
}
