<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260426181751 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE comment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(64) NOT NULL, content TEXT NOT NULL, note DOUBLE PRECISION NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, is_visible BOOLEAN NOT NULL, author_id INT NOT NULL, film_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9474526CF675F31B ON comment (author_id)');
        $this->addSql('CREATE INDEX IDX_9474526C567F5183 ON comment (film_id)');
        $this->addSql('CREATE TABLE comment_report (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, is_active BOOLEAN NOT NULL, statut VARCHAR(64) NOT NULL, comment_id INT NOT NULL, complainant_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E3C2F96F8697D13 ON comment_report (comment_id)');
        $this->addSql('CREATE INDEX IDX_E3C2F964C422040 ON comment_report (complainant_id)');
        $this->addSql('CREATE TABLE comment_report_user (comment_report_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (comment_report_id, user_id))');
        $this->addSql('CREATE INDEX IDX_C553FAF0A2AC4596 ON comment_report_user (comment_report_id)');
        $this->addSql('CREATE INDEX IDX_C553FAF0A76ED395 ON comment_report_user (user_id)');
        $this->addSql('ALTER TABLE comment ADD CONSTRAINT FK_9474526CF675F31B FOREIGN KEY (author_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE comment ADD CONSTRAINT FK_9474526C567F5183 FOREIGN KEY (film_id) REFERENCES film (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE comment_report ADD CONSTRAINT FK_E3C2F96F8697D13 FOREIGN KEY (comment_id) REFERENCES comment (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE comment_report ADD CONSTRAINT FK_E3C2F964C422040 FOREIGN KEY (complainant_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE comment_report_user ADD CONSTRAINT FK_C553FAF0A2AC4596 FOREIGN KEY (comment_report_id) REFERENCES comment_report (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE comment_report_user ADD CONSTRAINT FK_C553FAF0A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE comment DROP CONSTRAINT FK_9474526CF675F31B');
        $this->addSql('ALTER TABLE comment DROP CONSTRAINT FK_9474526C567F5183');
        $this->addSql('ALTER TABLE comment_report DROP CONSTRAINT FK_E3C2F96F8697D13');
        $this->addSql('ALTER TABLE comment_report DROP CONSTRAINT FK_E3C2F964C422040');
        $this->addSql('ALTER TABLE comment_report_user DROP CONSTRAINT FK_C553FAF0A2AC4596');
        $this->addSql('ALTER TABLE comment_report_user DROP CONSTRAINT FK_C553FAF0A76ED395');
        $this->addSql('DROP TABLE comment');
        $this->addSql('DROP TABLE comment_report');
        $this->addSql('DROP TABLE comment_report_user');
    }
}
