<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260422155324 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE carousel_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, position INT NOT NULL, film_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_33577A28567F5183 ON carousel_item (film_id)');
        $this->addSql('ALTER TABLE carousel_item ADD CONSTRAINT FK_33577A28567F5183 FOREIGN KEY (film_id) REFERENCES film (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE carousel_item DROP CONSTRAINT FK_33577A28567F5183');
        $this->addSql('DROP TABLE carousel_item');
    }
}
